name: connor-bot

services:
  redis:
    image: redis:7.2-alpine
    container_name: bot_redis
    restart: always
    command: redis-server --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: bot_backend
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    env_file: ./backend/.env
    environment:
      - DATABASE_URL=file:/app/data/bot.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    volumes:
      - sqlite_data:/app/data

  scraper:
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    container_name: bot_scraper
    restart: always
    ipc: host
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=file:/app/data/bot.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HEADLESS=true
      # UNCOMMENT AND FILL THIS TO USE PROXY
      # - PROXY_URL=http://username:password@proxy.example.com:8080
    volumes:
      - ./scraper/sessions:/app/sessions
      - sqlite_data:/app/data

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: bot_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/bot.db
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - sqlite_data:/app/data

volumes:
  redis_data:
  sqlite_data:
