name: connor-bot

services:
  redis:
    image: redis:7.2-alpine
    container_name: bot_redis
    restart: always
    command: redis-server --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  scraper:
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    container_name: bot_scraper
    restart: always
    ipc: host
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=file:/app/data/bot.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HEADLESS=true
      # - PROXY_URL=http://user:pass@host:port 
    volumes:
      - ./scraper/sessions:/app/sessions
      - sqlite_data:/app/data
      - ./scraper:/app/scraper:rw  # Hot Reloading

volumes:
  redis_data:
  sqlite_data: